/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var m = Object.defineProperty;
var O = Object.getOwnPropertyDescriptor;
var L = Object.getOwnPropertyNames;
var k = Object.prototype.hasOwnProperty;
var E = (r, t) => {
    for (var e in t) m(r, e, { get: t[e], enumerable: !0 });
  },
  S = (r, t, e, s) => {
    if ((t && typeof t == 'object') || typeof t == 'function')
      for (let o of L(t))
        !k.call(r, o) &&
          o !== e &&
          m(r, o, {
            get: () => t[o],
            enumerable: !(s = O(t, o)) || s.enumerable,
          });
    return r;
  };
var T = (r) => S(m({}, '__esModule', { value: !0 }), r);
var C = {};
E(C, { default: () => h });
module.exports = T(C);
var l = require('obsidian');
var $ = require('obsidian');
var x = require('obsidian');
function w() {
  let r = (0, x.getLanguage)();
  return r && r.toLowerCase().startsWith('zh') ? 'zh' : 'en';
}
function d(r) {
  let t = w();
  return _[t][r] || _.en[r] || r;
}
var _ = {
  en: {
    view_title: 'LaTeX snippets',
    search_placeholder: 'Search symbol code...',
    popout_tooltip: 'Open in pop-out window',
    dock_tooltip: 'Dock to sidebar',
    greek_letters: 'Greek',
    operators_and_relations: 'Operators and relations',
    arrows: 'Arrows',
    delimiters: 'Delimiters',
    maths_constructs: 'Maths constructs',
    variable_sized_symbols: 'Variable-sized symbols',
    standard_functions: 'Standard functions',
    letter_styles: 'Letter styles',
    misc: 'Miscellaneous',
    matrices: 'Matrices',
    environments: 'Environments',
    settings_json_name: 'Symbol configuration (JSON)',
    settings_json_desc:
      'Edit the JSON below to customize symbols. Each symbol can have an optional "cursorOffset" field: the character position where the cursor lands after insertion. If the offset exceeds the code length, spaces will be padded. If omitted, defaults to inserting a trailing space. Example: { "display": "$\\frac{a}{b}$", "code": "\\frac{}{}", "cursorOffset": 6 } \u2014 cursor lands inside the first {}.',
    settings_reset_name: 'Reset to defaults',
    settings_reset_desc:
      'Restore original symbol list. This will overwrite your changes.',
    settings_reset_btn: 'Reset',
    settings_reset_confirm:
      'Are you sure you want to reset all symbols to default?',
    settings_reset_success: 'Symbols reset to default.',
    json_error: 'Invalid JSON syntax',
  },
  zh: {
    view_title: 'LaTeX \u7247\u6BB5',
    search_placeholder: '\u641C\u7D22\u7B26\u53F7\u4EE3\u7801...',
    popout_tooltip: '\u5728\u6D6E\u52A8\u7A97\u53E3\u4E2D\u6253\u5F00',
    dock_tooltip: '\u505C\u9760\u81F3\u4FA7\u8FB9\u680F',
    greek_letters: '\u5E0C\u814A\u5B57\u6BCD',
    operators_and_relations: '\u8FD0\u7B97\u7B26\u4E0E\u5173\u7CFB',
    arrows: '\u7BAD\u5934',
    delimiters: '\u5206\u9694\u7B26',
    maths_constructs: '\u6570\u5B66\u7ED3\u6784',
    variable_sized_symbols: '\u53EF\u53D8\u5927\u5C0F\u7B26\u53F7',
    standard_functions: '\u6807\u51C6\u51FD\u6570',
    letter_styles: '\u5B57\u6BCD\u6837\u5F0F',
    misc: '\u6742\u9879',
    matrices: '\u77E9\u9635',
    environments: '\u6570\u5B66\u73AF\u5883',
    settings_json_name: '\u7B26\u53F7\u914D\u7F6E (JSON)',
    settings_json_desc:
      '\u5728\u4E0B\u65B9\u7F16\u8F91 JSON \u4EE5\u81EA\u5B9A\u4E49\u7B26\u53F7\u3002\u6BCF\u4E2A\u7B26\u53F7\u53EF\u6DFB\u52A0\u53EF\u9009\u5B57\u6BB5 "cursorOffset"\uFF1A\u63D2\u5165\u540E\u5149\u6807\u505C\u7559\u7684\u5B57\u7B26\u4F4D\u7F6E\u3002\u82E5\u504F\u79FB\u91CF\u8D85\u51FA\u4EE3\u7801\u957F\u5EA6\u5219\u81EA\u52A8\u8865\u7A7A\u683C\uFF1B\u82E5\u4E0D\u586B\u5219\u9ED8\u8BA4\u672B\u5C3E\u52A0\u7A7A\u683C\u3002\u793A\u4F8B\uFF1A{ "display": "$\\frac{a}{b}$", "code": "\\frac{}{}", "cursorOffset": 6 } \u2014 \u5149\u6807\u505C\u7559\u5728\u7B2C\u4E00\u4E2A {} \u5185\u90E8\u3002',
    settings_reset_name: '\u91CD\u7F6E\u4E3A\u9ED8\u8BA4',
    settings_reset_desc:
      '\u6062\u590D\u521D\u59CB\u7B26\u53F7\u5217\u8868\u3002\u8FD9\u5C06\u8986\u76D6\u60A8\u7684\u6240\u6709\u66F4\u6539\u3002',
    settings_reset_btn: '\u91CD\u7F6E',
    settings_reset_confirm:
      '\u786E\u5B9A\u8981\u5C06\u6240\u6709\u7B26\u53F7\u91CD\u7F6E\u4E3A\u9ED8\u8BA4\u503C\u5417\uFF1F',
    settings_reset_success:
      '\u7B26\u53F7\u5DF2\u91CD\u7F6E\u4E3A\u9ED8\u8BA4\u503C\u3002',
    json_error: 'JSON \u8BED\u6CD5\u9519\u8BEF',
  },
};
var p = 'latex-panel-view',
  u = class extends $.ItemView {
    constructor(t, e) {
      (super(t),
        (this.plugin = e),
        (this.currentCategory =
          Object.keys(this.plugin.settings.symbols)[0] || ''),
        (this.searchTerm = ''),
        (this.isPopout = !1));
    }
    getViewType() {
      return p;
    }
    getDisplayText() {
      return d('view_title');
    }
    refresh() {
      let t = this.contentEl,
        e = Object.keys(this.plugin.settings.symbols);
      (e.includes(this.currentCategory) || (this.currentCategory = e[0] || ''),
        this.renderSymbols(t));
    }
    updateActionButtonUI() {
      this.actionButtonEl &&
        (this.isPopout
          ? ((0, $.setIcon)(this.actionButtonEl, 'panel-left-close'),
            (this.actionButtonEl.ariaLabel = d('dock_tooltip')))
          : ((0, $.setIcon)(this.actionButtonEl, 'popup-open'),
            (this.actionButtonEl.ariaLabel = d('popout_tooltip'))));
    }
    getSymbolDisplayText(t) {
      if (typeof t.display == 'string') return t.display;
      {
        let e = w();
        return t.display[e] || t.display.en;
      }
    }
    async onOpen() {
      let t = this.contentEl;
      (t.empty(),
        await Promise.resolve(),
        this.setupControls(t),
        this.registerDomEvent(t, 'mousedown', (e) => {
          let o = e.target.closest('.latex-symbol-button');
          if (o != null && o.dataset.code) {
            (e.preventDefault(), e.stopPropagation());
            let a = o.dataset.cursorOffset;
            this.insertText(
              o.dataset.code,
              a !== void 0 ? parseInt(a, 10) : void 0,
            );
          }
        }),
        this.renderSymbols(t));
    }
    setupControls(t) {
      let e = t.createDiv({ cls: 'latex-controls-container' }),
        s = e.createDiv({ cls: 'latex-top-row' }),
        o = s.createEl('input', {
          type: 'text',
          placeholder: d('search_placeholder'),
          cls: 'latex-search-input',
        });
      ((this.actionButtonEl = s.createEl('button', {
        cls: 'latex-action-button',
      })),
        this.updateActionButtonUI(),
        this.registerDomEvent(this.actionButtonEl, 'mousedown', (i) => {
          (i.preventDefault(),
            this.isPopout ? this.dockView() : this.popoutView());
        }));
      let a = e.createEl('select', { cls: 'latex-category-select' });
      (Object.keys(this.plugin.settings.symbols).forEach((i) => {
        let n = a.createEl('option');
        ((n.value = i), (n.textContent = d(i)));
      }),
        this.registerDomEvent(a, 'change', (i) => {
          ((this.currentCategory = i.target.value), this.renderSymbols(t));
        }),
        (a.value = this.currentCategory),
        this.registerDomEvent(o, 'input', (i) => {
          ((this.searchTerm = i.target.value.toLowerCase()),
            this.renderSymbols(t));
        }));
    }
    renderSymbols(t) {
      let e = t.querySelector('.latex-content-container');
      (e || (e = t.createDiv({ cls: 'latex-content-container' })), e.empty());
      let s = this.plugin.settings.symbols[this.currentCategory];
      if (!s) return;
      let o = s.filter((c) => c.code.toLowerCase().includes(this.searchTerm)),
        a = e.createDiv({ cls: 'latex-grid' });
      o.forEach((c) => {
        let i =
            this.currentCategory === 'matrices' ||
            this.currentCategory === 'environments',
          n = a.createEl('button', {
            cls: `latex-symbol-button ${i ? 'latex-translated-button' : 'latex-formula-button'}`,
            attr: { 'data-category': this.currentCategory },
          }),
          y = this.getSymbolDisplayText(c);
        (i
          ? n.createDiv({ cls: 'latex-translated-text' }).setText(y)
          : $.MarkdownRenderer.render(this.app, y, n, '', this),
          n.setAttr('data-code', c.code),
          c.cursorOffset !== void 0 &&
            n.setAttr('data-cursor-offset', String(c.cursorOffset)));
      });
    }
    async popoutView() {
      let t = this.app.workspace.openPopoutLeaf();
      await t.setViewState({ type: p, active: !0 });
      let e = t.view;
      ((e.isPopout = !0), e.updateActionButtonUI(), this.leaf.detach());
    }
    async dockView() {
      let t = this.app.workspace.getRightLeaf(!1);
      if (t) {
        await t.setViewState({ type: p, active: !0 });
        let e = t.view;
        ((e.isPopout = !1),
          e.updateActionButtonUI(),
          await this.app.workspace.revealLeaf(t),
          this.leaf.detach());
      }
    }
    insertText(t, e) {
      let s = this.plugin.lastActiveMarkdownView;
      if (!s) {
        let o = this.app.workspace.getLeavesOfType('markdown');
        return o.length > 0 ? this.insertTextFallback(t, e, o[0].view) : void 0;
      }
      this.doInsertText(s, t, e);
    }
    doInsertText(t, e, s) {
      let o = t.editor;
      o.hasFocus() || o.focus();
      let a = o.getCursor(),
        c = a.ch,
        i,
        n;
      if (s !== void 0)
        if (((i = e), s <= e.length)) n = s;
        else {
          let y = ' '.repeat(s - e.length);
          ((i = e + y), (n = s));
        }
      else ((i = e + ' '), (n = e.length + 1));
      (o.replaceSelection(i), o.setCursor(a.line, c + n));
    }
    insertTextFallback(t, e, s) {
      this.doInsertText(s, t, e);
    }
    async onClose() {}
  };
var f = {
  greek_letters: [
    { display: '$\\alpha$', code: '\\alpha' },
    { display: '$\\beta$', code: '\\beta' },
    { display: '$\\gamma$', code: '\\gamma' },
    { display: '$\\delta$', code: '\\delta' },
    { display: '$\\epsilon$', code: '\\epsilon' },
    { display: '$\\zeta$', code: '\\zeta' },
    { display: '$\\eta$', code: '\\eta' },
    { display: '$\\theta$', code: '\\theta' },
    { display: '$\\iota$', code: '\\iota' },
    { display: '$\\kappa$', code: '\\kappa' },
    { display: '$\\lambda$', code: '\\lambda' },
    { display: '$\\mu$', code: '\\mu' },
    { display: '$\\nu$', code: '\\nu' },
    { display: '$\\xi$', code: '\\xi' },
    { display: '$\\omicron$', code: '\\omicron' },
    { display: '$\\pi$', code: '\\pi' },
    { display: '$\\rho$', code: '\\rho' },
    { display: '$\\sigma$', code: '\\sigma' },
    { display: '$\\tau$', code: '\\tau' },
    { display: '$\\upsilon$', code: '\\upsilon' },
    { display: '$\\phi$', code: '\\phi' },
    { display: '$\\chi$', code: '\\chi' },
    { display: '$\\psi$', code: '\\psi' },
    { display: '$\\omega$', code: '\\omega' },
    { display: '$\\Gamma$', code: '\\Gamma' },
    { display: '$\\Delta$', code: '\\Delta' },
    { display: '$\\Theta$', code: '\\Theta' },
    { display: '$\\Lambda$', code: '\\Lambda' },
    { display: '$\\Xi$', code: '\\Xi' },
    { display: '$\\Pi$', code: '\\Pi' },
    { display: '$\\Sigma$', code: '\\Sigma' },
    { display: '$\\Upsilon$', code: '\\Upsilon' },
    { display: '$\\Phi$', code: '\\Phi' },
    { display: '$\\Psi$', code: '\\Psi' },
    { display: '$\\Omega$', code: '\\Omega' },
    { display: '$\\varepsilon$', code: '\\varepsilon' },
    { display: '$\\vartheta$', code: '\\vartheta' },
    { display: '$\\varpi$', code: '\\varpi' },
    { display: '$\\varrho$', code: '\\varrho' },
    { display: '$\\varsigma$', code: '\\varsigma' },
    { display: '$\\varphi$', code: '\\varphi' },
  ],
  operators_and_relations: [
    { display: '$\\pm$', code: '\\pm' },
    { display: '$\\mp$', code: '\\mp' },
    { display: '$\\times$', code: '\\times' },
    { display: '$\\div$', code: '\\div' },
    { display: '$\\ast$', code: '\\ast' },
    { display: '$\\cdot$', code: '\\cdot' },
    { display: '$\\circ$', code: '\\circ' },
    { display: '$\\bullet$', code: '\\bullet' },
    { display: '$\\leq$', code: '\\leq' },
    { display: '$\\geq$', code: '\\geq' },
    { display: '$\\neq$', code: '\\neq' },
    { display: '$\\approx$', code: '\\approx' },
    { display: '$\\equiv$', code: '\\equiv' },
    { display: '$\\sim$', code: '\\sim' },
    { display: '$\\simeq$', code: '\\simeq' },
    { display: '$\\propto$', code: '\\propto' },
    { display: '$\\in$', code: '\\in' },
    { display: '$\\notin$', code: '\\notin' },
    { display: '$\\subset$', code: '\\subset' },
    { display: '$\\supset$', code: '\\supset' },
    { display: '$\\subseteq$', code: '\\subseteq' },
    { display: '$\\supseteq$', code: '\\supseteq' },
    { display: '$\\cap$', code: '\\cap' },
    { display: '$\\cup$', code: '\\cup' },
    { display: '$\\forall$', code: '\\forall' },
    { display: '$\\exists$', code: '\\exists' },
    { display: '$\\nabla$', code: '\\nabla' },
    { display: '$\\partial$', code: '\\partial' },
    { display: '$\\wedge$', code: '\\wedge' },
    { display: '$\\vee$', code: '\\vee' },
    { display: '$\\neg$', code: '\\neg' },
    { display: '$\\prec$', code: '\\prec' },
    { display: '$\\succ$', code: '\\succ' },
    { display: '$\\preceq$', code: '\\preceq' },
    { display: '$\\succeq$', code: '\\succeq' },
    { display: '$\\ll$', code: '\\ll' },
    { display: '$\\gg$', code: '\\gg' },
    { display: '$\\parallel$', code: '\\parallel' },
    { display: '$\\nparallel$', code: '\\nparallel' },
    { display: '$\\perp$', code: '\\perp' },
  ],
  arrows: [
    { display: '$\\leftarrow$', code: '\\leftarrow' },
    { display: '$\\rightarrow$', code: '\\rightarrow' },
    { display: '$\\leftrightarrow$', code: '\\leftrightarrow' },
    { display: '$\\Leftarrow$', code: '\\Leftarrow' },
    { display: '$\\Rightarrow$', code: '\\Rightarrow' },
    { display: '$\\Leftrightarrow$', code: '\\Leftrightarrow' },
    { display: '$\\uparrow$', code: '\\uparrow' },
    { display: '$\\downarrow$', code: '\\downarrow' },
    { display: '$\\updownarrow$', code: '\\updownarrow' },
    { display: '$\\Uparrow$', code: '\\Uparrow' },
    { display: '$\\Downarrow$', code: '\\Downarrow' },
    { display: '$\\Updownarrow$', code: '\\Updownarrow' },
    { display: '$\\longleftarrow$', code: '\\longleftarrow' },
    { display: '$\\longrightarrow$', code: '\\longrightarrow' },
    { display: '$\\longleftrightarrow$', code: '\\longleftrightarrow' },
    { display: '$\\Longleftarrow$', code: '\\Longleftarrow' },
    { display: '$\\Longrightarrow$', code: '\\Longrightarrow' },
    { display: '$\\Longleftrightarrow$', code: '\\Longleftrightarrow' },
    { display: '$\\mapsto$', code: '\\mapsto' },
    { display: '$\\hookrightarrow$', code: '\\hookrightarrow' },
    { display: '$\\hookleftarrow$', code: '\\hookleftarrow' },
    { display: '$\\nearrow$', code: '\\nearrow' },
    { display: '$\\searrow$', code: '\\searrow' },
    { display: '$\\swarrow$', code: '\\swarrow' },
    { display: '$\\nwarrow$', code: '\\nwarrow' },
    { display: '$\\leadsto$', code: '\\leadsto' },
  ],
  delimiters: [
    { display: '$()$', code: '()', cursorOffset: 1 },
    { display: '$[]$', code: '[]', cursorOffset: 1 },
    { display: '$\\{\\}$', code: '\\{\\}', cursorOffset: 2 },
    { display: '$||$', code: '||', cursorOffset: 1 },
    {
      display: '$\\langle\\rangle$',
      code: '\\langle\\rangle',
      cursorOffset: 7,
    },
    {
      display: '$\\lfloor\\rfloor$',
      code: '\\lfloor \\rfloor',
      cursorOffset: 7,
    },
    { display: '$\\lceil\\rceil$', code: '\\lceil \\rceil', cursorOffset: 6 },
    { display: '$\\vert$', code: '\\vert' },
    { display: '$\\Vert$', code: '\\Vert' },
    { display: '$\\ulcorner$', code: '\\ulcorner' },
    { display: '$\\urcorner$', code: '\\urcorner' },
    { display: '$\\llcorner$', code: '\\llcorner' },
    { display: '$\\lrcorner$', code: '\\lrcorner' },
    {
      display: '$\\uparrow\\downarrow$',
      code: '\\uparrow\\downarrow',
      cursorOffset: 8,
    },
  ],
  maths_constructs: [
    { display: '$x^{2}$', code: '^{}', cursorOffset: 2 },
    { display: '$x_{i}$', code: '_{}', cursorOffset: 2 },
    { display: '$\\frac{a}{b}$', code: '\\frac{}{}', cursorOffset: 6 },
    { display: '$\\sqrt{x}$', code: '\\sqrt{}', cursorOffset: 6 },
    { display: '$\\sqrt[n]{x}$', code: '\\sqrt[]{-}', cursorOffset: 6 },
    { display: '$\\overline{x}$', code: '\\overline{}', cursorOffset: 10 },
    { display: '$\\vec{x}$', code: '\\vec{}', cursorOffset: 5 },
    { display: '$\\hat{x}$', code: '\\hat{}', cursorOffset: 5 },
    { display: '$\\tilde{x}$', code: '\\tilde{}', cursorOffset: 7 },
    { display: '$\\dot{x}$', code: '\\dot{}', cursorOffset: 5 },
    { display: '$\\ddot{x}$', code: '\\ddot{}', cursorOffset: 6 },
    {
      display: '$\\overleftarrow{x}$',
      code: '\\overleftarrow{}',
      cursorOffset: 15,
    },
    {
      display: '$\\overrightarrow{x}$',
      code: '\\overrightarrow{}',
      cursorOffset: 16,
    },
    { display: '$\\overbrace{x}$', code: '\\overbrace{}', cursorOffset: 11 },
    { display: '$\\underbrace{x}$', code: '\\underbrace{}', cursorOffset: 12 },
    { display: '$\\stackrel{x}{y}$', code: '\\stackrel{}{}', cursorOffset: 10 },
    { display: '$\\overset{x}{y}$', code: '\\overset{}{}', cursorOffset: 9 },
    { display: '$\\underset{x}{y}$', code: '\\underset{}{}', cursorOffset: 10 },
  ],
  variable_sized_symbols: [
    { display: '$\\sum$', code: '\\sum' },
    { display: '$\\prod$', code: '\\prod' },
    { display: '$\\coprod$', code: '\\coprod' },
    { display: '$\\int$', code: '\\int' },
    { display: '$\\oint$', code: '\\oint' },
    { display: '$\\bigcup$', code: '\\bigcup' },
    { display: '$\\bigcap$', code: '\\bigcap' },
    { display: '$\\bigoplus$', code: '\\bigoplus' },
    { display: '$\\bigotimes$', code: '\\bigotimes' },
    { display: '$\\bigvee$', code: '\\bigvee' },
    { display: '$\\bigwedge$', code: '\\bigwedge' },
    { display: '$\\iint$', code: '\\iint' },
    { display: '$\\iiint$', code: '\\iiint' },
    { display: '$\\iiiint$', code: '\\iiiint' },
    { display: '$\\idotsint$', code: '\\idotsint' },
    { display: '$\u222E$', code: '\u222E' },
    { display: '$\u222F$', code: '\u222F' },
    { display: '$\u2230$', code: '\u2230' },
    { display: '$\u2231$', code: '\u2231' },
    { display: '$\u2232$', code: '\u2232' },
    { display: '$\u2233$', code: '\u2233' },
    { display: '$\\biguplus$', code: '\\biguplus' },
    { display: '$\\bigodot$', code: '\\bigodot' },
  ],
  standard_functions: [
    { display: '$\\sin$', code: '\\sin' },
    { display: '$\\cos$', code: '\\cos' },
    { display: '$\\tan$', code: '\\tan' },
    { display: '$\\csc$', code: '\\csc' },
    { display: '$\\sec$', code: '\\sec' },
    { display: '$\\cot$', code: '\\cot' },
    { display: '$\\arcsin$', code: '\\arcsin' },
    { display: '$\\arccos$', code: '\\arccos' },
    { display: '$\\arctan$', code: '\\arctan' },
    { display: '$\\sinh$', code: '\\sinh' },
    { display: '$\\cosh$', code: '\\cosh' },
    { display: '$\\tanh$', code: '\\tanh' },
    { display: '$\\lim$', code: '\\lim' },
    { display: '$\\min$', code: '\\min' },
    { display: '$\\max$', code: '\\max' },
    { display: '$\\inf$', code: '\\inf' },
    { display: '$\\sup$', code: '\\sup' },
    { display: '$\\log$', code: '\\log' },
    { display: '$\\ln$', code: '\\ln' },
    { display: '$\\det$', code: '\\det' },
    { display: '$\\exp$', code: '\\exp' },
    { display: '$\\deg$', code: '\\deg' },
    { display: '$\\gcd$', code: '\\gcd' },
    { display: '$\\ker$', code: '\\ker' },
    { display: '$\\dim$', code: '\\dim' },
    { display: '$\\hom$', code: '\\hom' },
    { display: '$\\arg$', code: '\\arg' },
  ],
  letter_styles: [
    { display: '$\\mathbb{A}$', code: '\\mathbb{}', cursorOffset: 8 },
    { display: '$\\mathcal{A}$', code: '\\mathcal{}', cursorOffset: 9 },
    { display: '$\\mathfrak{A}$', code: '\\mathfrak{}', cursorOffset: 10 },
    { display: '$\\mathscr{A}$', code: '\\mathscr{}', cursorOffset: 12 },
    { display: '$\\mathbf{A}$', code: '\\mathbf{}', cursorOffset: 8 },
    { display: '$\\mathrm{A}$', code: '\\mathrm{}', cursorOffset: 8 },
    { display: '$\\mathit{A}$', code: '\\mathit{}', cursorOffset: 8 },
    { display: '$\\mathsf{A}$', code: '\\mathsf{}', cursorOffset: 8 },
    { display: '$\\mathtt{A}$', code: '\\mathtt{}', cursorOffset: 8 },
    { display: '$\\boldsymbol{A}$', code: '\\boldsymbol{}', cursorOffset: 12 },
  ],
  matrices: [
    {
      display: { en: 'Basic matrix', zh: '\u57FA\u7840\u77E9\u9635' },
      code: `\\begin{matrix}
a & b \\\\
c & d
\\end{matrix}`,
      cursorOffset: 15,
    },
    {
      display: {
        en: 'Parentheses matrix',
        zh: '\u5C0F\u62EC\u53F7\u77E9\u9635',
      },
      code: `\\begin{pmatrix}
a & b \\\\
c & d
\\end{pmatrix}`,
      cursorOffset: 16,
    },
    {
      display: { en: 'Bracket matrix', zh: '\u4E2D\u62EC\u53F7\u77E9\u9635' },
      code: `\\begin{bmatrix}
a & b \\\\
c & d
\\end{bmatrix}`,
      cursorOffset: 16,
    },
    {
      display: {
        en: 'Single line matrix',
        zh: '\u5355\u7AD6\u7EBF\u77E9\u9635',
      },
      code: `\\begin{vmatrix}
a & b \\\\
c & d
\\end{vmatrix}`,
      cursorOffset: 16,
    },
    {
      display: {
        en: 'Double line matrix',
        zh: '\u53CC\u7AD6\u7EBF\u77E9\u9635',
      },
      code: `\\begin{Vmatrix}
a & b \\\\
c & d
\\end{Vmatrix}`,
      cursorOffset: 16,
    },
  ],
  misc: [
    { display: '$\\infty$', code: '\\infty' },
    { display: '$\\hbar$', code: '\\hbar' },
    { display: '$\\ell$', code: '\\ell' },
    { display: '$\\wp$', code: '\\wp' },
    { display: '$\\emptyset$', code: '\\emptyset' },
    { display: '$\\ldots$', code: '\\ldots' },
    { display: '$\\cdots$', code: '\\cdots' },
    { display: '$\\vdots$', code: '\\vdots' },
    { display: '$\\ddots$', code: '\\ddots' },
    { display: '$\\eth$', code: '\\eth' },
    { display: '$\\mho$', code: '\\mho' },
    { display: '$\\partial$', code: '\\partial' },
    { display: '$\\nabla$', code: '\\nabla' },
    { display: '$\\square$', code: '\\square' },
    { display: '$\\blacksquare$', code: '\\blacksquare' },
    { display: '$\\triangle$', code: '\\triangle' },
    { display: '$\\blacktriangle$', code: '\\blacktriangle' },
    { display: '$\\diamondsuit$', code: '\\diamondsuit' },
    { display: '$\\heartsuit$', code: '\\heartsuit' },
    { display: '$\\clubsuit$', code: '\\clubsuit' },
    { display: '$\\spadesuit$', code: '\\spadesuit' },
  ],
  environments: [
    {
      display: { en: 'Equation', zh: '\u5E26\u7F16\u53F7\u65B9\u7A0B' },
      code: `\\begin{equation}

\\end{equation}`,
      cursorOffset: 17,
    },
    {
      display: { en: 'Align', zh: '\u5BF9\u9F50\u65B9\u7A0B\u7EC4' },
      code: `\\begin{align}

\\end{align}`,
      cursorOffset: 12,
    },
    {
      display: { en: 'Cases', zh: '\u5206\u6BB5\u51FD\u6570' },
      code: `\\begin{cases}

\\end{cases}`,
      cursorOffset: 14,
    },
    {
      display: { en: 'Array', zh: '\u77E9\u9635\u6570\u7EC4' },
      code: `\\begin{array}{}

\\end{array}`,
      cursorOffset: 15,
    },
  ],
};
var h = class extends l.Plugin {
    constructor() {
      super(...arguments);
      this.lastActiveMarkdownView = null;
    }
    async onload() {
      (await this.loadSettings(),
        this.registerView(p, (e) => new u(e, this)),
        this.registerEvent(
          this.app.workspace.on('active-leaf-change', (e) => {
            (e == null ? void 0 : e.view) instanceof l.MarkdownView &&
              (this.lastActiveMarkdownView = e.view);
          }),
        ),
        this.addCommand({
          id: 'open-latex-panel',
          name: 'Open LaTeX panel',
          callback: () => {
            this.activateView();
          },
        }),
        this.addRibbonIcon('sigma', 'Open LaTeX panel', () => {
          this.activateView();
        }),
        this.addSettingTab(new v(this.app, this)));
    }
    async activateView() {
      let { workspace: e } = this.app,
        s = null,
        o = e.getLeavesOfType(p);
      (o.length > 0
        ? (s = o[0])
        : ((s = e.getRightLeaf(!1)),
          s && (await s.setViewState({ type: p, active: !0 }))),
        s && (await e.revealLeaf(s)));
    }
    async loadSettings() {
      var o;
      let e = await this.loadData(),
        s = { symbols: {} };
      for (let a of Object.keys(f)) {
        let c = f[a],
          i = (o = e == null ? void 0 : e.symbols) == null ? void 0 : o[a];
        i
          ? (s.symbols[a] = i.map((n, y) => {
              let g = c[y];
              return g && g.code === n.code ? { ...g, ...n } : n;
            }))
          : (s.symbols[a] = c);
      }
      if (e != null && e.symbols)
        for (let a of Object.keys(e.symbols))
          s.symbols[a] || (s.symbols[a] = e.symbols[a]);
      this.settings = s;
    }
    async saveSettings() {
      (await this.saveData(this.settings),
        this.app.workspace.getLeavesOfType(p).forEach((s) => {
          s.view instanceof u && s.view.refresh();
        }));
    }
    onunload() {}
  },
  b = class extends l.Modal {
    constructor(t, e, s, o) {
      (super(t), (this.title = e), (this.content = s), (this.onConfirm = o));
    }
    onOpen() {
      let { contentEl: t } = this;
      (t.createEl('h2', { text: this.title }),
        t.createDiv({ text: this.content }));
      let e = t.createDiv({ cls: 'modal-button-container' });
      new l.Setting(e)
        .addButton((s) => s.setButtonText('Cancel').onClick(() => this.close()))
        .addButton((s) =>
          s
            .setButtonText('Confirm')
            .setWarning()
            .onClick(async () => {
              (await this.onConfirm(), this.close());
            }),
        );
    }
    onClose() {
      let { contentEl: t } = this;
      t.empty();
    }
  },
  v = class extends l.PluginSettingTab {
    constructor(t, e) {
      (super(t, e), (this.plugin = e));
    }
    display() {
      let { containerEl: t } = this;
      (t.empty(),
        new l.Setting(t)
          .setName(d('settings_json_name'))
          .setDesc(d('settings_json_desc')),
        new l.Setting(t)
          .setClass('latex-helper-json-textarea')
          .addTextArea((e) =>
            e
              .setPlaceholder('Paste your JSON here...')
              .setValue(JSON.stringify(this.plugin.settings.symbols, null, 2))
              .onChange(async (s) => {
                try {
                  let o = JSON.parse(s);
                  ((this.plugin.settings.symbols = o),
                    await this.plugin.saveSettings());
                } catch (o) {
                  console.warn(d('json_error'));
                }
              }),
          ),
        new l.Setting(t)
          .setName(d('settings_reset_name'))
          .setDesc(d('settings_reset_desc'))
          .addButton((e) =>
            e
              .setButtonText(d('settings_reset_btn'))
              .setWarning()
              .onClick(() => {
                new b(
                  this.app,
                  d('settings_reset_name'),
                  d('settings_reset_confirm'),
                  async () => {
                    ((this.plugin.settings.symbols = f),
                      await this.plugin.saveSettings(),
                      this.display(),
                      new l.Notice(d('settings_reset_success')));
                  },
                ).open();
              }),
          ));
    }
  };

/* nosourcemap */
