/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiKitRouteRouteImport } from './routes/ui-kit/route'
import { Route as ModernRouteRouteImport } from './routes/modern/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiKitIndexRouteImport } from './routes/ui-kit/index'
import { Route as ModernIndexRouteImport } from './routes/modern/index'
import { Route as UiKitWebglTentacleFooterRouteImport } from './routes/ui-kit/webgl-tentacle-footer'
import { Route as UiKitSliderRouteImport } from './routes/ui-kit/slider'

const UiKitRouteRoute = UiKitRouteRouteImport.update({
  id: '/ui-kit',
  path: '/ui-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ModernRouteRoute = ModernRouteRouteImport.update({
  id: '/modern',
  path: '/modern',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiKitIndexRoute = UiKitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UiKitRouteRoute,
} as any)
const ModernIndexRoute = ModernIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModernRouteRoute,
} as any)
const UiKitWebglTentacleFooterRoute =
  UiKitWebglTentacleFooterRouteImport.update({
    id: '/webgl-tentacle-footer',
    path: '/webgl-tentacle-footer',
    getParentRoute: () => UiKitRouteRoute,
  } as any)
const UiKitSliderRoute = UiKitSliderRouteImport.update({
  id: '/slider',
  path: '/slider',
  getParentRoute: () => UiKitRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modern': typeof ModernRouteRouteWithChildren
  '/ui-kit': typeof UiKitRouteRouteWithChildren
  '/ui-kit/slider': typeof UiKitSliderRoute
  '/ui-kit/webgl-tentacle-footer': typeof UiKitWebglTentacleFooterRoute
  '/modern/': typeof ModernIndexRoute
  '/ui-kit/': typeof UiKitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ui-kit/slider': typeof UiKitSliderRoute
  '/ui-kit/webgl-tentacle-footer': typeof UiKitWebglTentacleFooterRoute
  '/modern': typeof ModernIndexRoute
  '/ui-kit': typeof UiKitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modern': typeof ModernRouteRouteWithChildren
  '/ui-kit': typeof UiKitRouteRouteWithChildren
  '/ui-kit/slider': typeof UiKitSliderRoute
  '/ui-kit/webgl-tentacle-footer': typeof UiKitWebglTentacleFooterRoute
  '/modern/': typeof ModernIndexRoute
  '/ui-kit/': typeof UiKitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/modern'
    | '/ui-kit'
    | '/ui-kit/slider'
    | '/ui-kit/webgl-tentacle-footer'
    | '/modern/'
    | '/ui-kit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ui-kit/slider'
    | '/ui-kit/webgl-tentacle-footer'
    | '/modern'
    | '/ui-kit'
  id:
    | '__root__'
    | '/'
    | '/modern'
    | '/ui-kit'
    | '/ui-kit/slider'
    | '/ui-kit/webgl-tentacle-footer'
    | '/modern/'
    | '/ui-kit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModernRouteRoute: typeof ModernRouteRouteWithChildren
  UiKitRouteRoute: typeof UiKitRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui-kit': {
      id: '/ui-kit'
      path: '/ui-kit'
      fullPath: '/ui-kit'
      preLoaderRoute: typeof UiKitRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modern': {
      id: '/modern'
      path: '/modern'
      fullPath: '/modern'
      preLoaderRoute: typeof ModernRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-kit/': {
      id: '/ui-kit/'
      path: '/'
      fullPath: '/ui-kit/'
      preLoaderRoute: typeof UiKitIndexRouteImport
      parentRoute: typeof UiKitRouteRoute
    }
    '/modern/': {
      id: '/modern/'
      path: '/'
      fullPath: '/modern/'
      preLoaderRoute: typeof ModernIndexRouteImport
      parentRoute: typeof ModernRouteRoute
    }
    '/ui-kit/webgl-tentacle-footer': {
      id: '/ui-kit/webgl-tentacle-footer'
      path: '/webgl-tentacle-footer'
      fullPath: '/ui-kit/webgl-tentacle-footer'
      preLoaderRoute: typeof UiKitWebglTentacleFooterRouteImport
      parentRoute: typeof UiKitRouteRoute
    }
    '/ui-kit/slider': {
      id: '/ui-kit/slider'
      path: '/slider'
      fullPath: '/ui-kit/slider'
      preLoaderRoute: typeof UiKitSliderRouteImport
      parentRoute: typeof UiKitRouteRoute
    }
  }
}

interface ModernRouteRouteChildren {
  ModernIndexRoute: typeof ModernIndexRoute
}

const ModernRouteRouteChildren: ModernRouteRouteChildren = {
  ModernIndexRoute: ModernIndexRoute,
}

const ModernRouteRouteWithChildren = ModernRouteRoute._addFileChildren(
  ModernRouteRouteChildren,
)

interface UiKitRouteRouteChildren {
  UiKitSliderRoute: typeof UiKitSliderRoute
  UiKitWebglTentacleFooterRoute: typeof UiKitWebglTentacleFooterRoute
  UiKitIndexRoute: typeof UiKitIndexRoute
}

const UiKitRouteRouteChildren: UiKitRouteRouteChildren = {
  UiKitSliderRoute: UiKitSliderRoute,
  UiKitWebglTentacleFooterRoute: UiKitWebglTentacleFooterRoute,
  UiKitIndexRoute: UiKitIndexRoute,
}

const UiKitRouteRouteWithChildren = UiKitRouteRoute._addFileChildren(
  UiKitRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModernRouteRoute: ModernRouteRouteWithChildren,
  UiKitRouteRoute: UiKitRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
