/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShrinesRouteImport } from './routes/shrines'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ArtRouteImport } from './routes/art'
import { Route as AboutRouteImport } from './routes/about'
import { Route as UiKitRouteRouteImport } from './routes/ui-kit/route'
import { Route as ModernRouteRouteImport } from './routes/modern/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiKitIndexRouteImport } from './routes/ui-kit/index'
import { Route as ModernIndexRouteImport } from './routes/modern/index'
import { Route as UiKitWebglTentacleFooterRouteImport } from './routes/ui-kit/webgl-tentacle-footer'
import { Route as UiKitSliderRouteImport } from './routes/ui-kit/slider'
import { Route as ModernShrinesRouteImport } from './routes/modern/shrines'
import { Route as ModernProjectsRouteImport } from './routes/modern/projects'
import { Route as ModernExperienceRouteImport } from './routes/modern/experience'
import { Route as ModernContactRouteImport } from './routes/modern/contact'
import { Route as ModernCaseStudiesRouteImport } from './routes/modern/case-studies'
import { Route as ModernArtRouteImport } from './routes/modern/art'
import { Route as ModernAboutRouteImport } from './routes/modern/about'
import { Route as ModernCaseStudiesIndexRouteImport } from './routes/modern/case-studies.index'
import { Route as ModernCaseStudiesSlugRouteImport } from './routes/modern/case-studies.$slug'

const ShrinesRoute = ShrinesRouteImport.update({
  id: '/shrines',
  path: '/shrines',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtRoute = ArtRouteImport.update({
  id: '/art',
  path: '/art',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const UiKitRouteRoute = UiKitRouteRouteImport.update({
  id: '/ui-kit',
  path: '/ui-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ModernRouteRoute = ModernRouteRouteImport.update({
  id: '/modern',
  path: '/modern',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiKitIndexRoute = UiKitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UiKitRouteRoute,
} as any)
const ModernIndexRoute = ModernIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModernRouteRoute,
} as any)
const UiKitWebglTentacleFooterRoute =
  UiKitWebglTentacleFooterRouteImport.update({
    id: '/webgl-tentacle-footer',
    path: '/webgl-tentacle-footer',
    getParentRoute: () => UiKitRouteRoute,
  } as any)
const UiKitSliderRoute = UiKitSliderRouteImport.update({
  id: '/slider',
  path: '/slider',
  getParentRoute: () => UiKitRouteRoute,
} as any)
const ModernShrinesRoute = ModernShrinesRouteImport.update({
  id: '/shrines',
  path: '/shrines',
  getParentRoute: () => ModernRouteRoute,
} as any)
const ModernProjectsRoute = ModernProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ModernRouteRoute,
} as any)
const ModernExperienceRoute = ModernExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => ModernRouteRoute,
} as any)
const ModernContactRoute = ModernContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ModernRouteRoute,
} as any)
const ModernCaseStudiesRoute = ModernCaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => ModernRouteRoute,
} as any)
const ModernArtRoute = ModernArtRouteImport.update({
  id: '/art',
  path: '/art',
  getParentRoute: () => ModernRouteRoute,
} as any)
const ModernAboutRoute = ModernAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ModernRouteRoute,
} as any)
const ModernCaseStudiesIndexRoute = ModernCaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModernCaseStudiesRoute,
} as any)
const ModernCaseStudiesSlugRoute = ModernCaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ModernCaseStudiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modern': typeof ModernRouteRouteWithChildren
  '/ui-kit': typeof UiKitRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/art': typeof ArtRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/shrines': typeof ShrinesRoute
  '/modern/about': typeof ModernAboutRoute
  '/modern/art': typeof ModernArtRoute
  '/modern/case-studies': typeof ModernCaseStudiesRouteWithChildren
  '/modern/contact': typeof ModernContactRoute
  '/modern/experience': typeof ModernExperienceRoute
  '/modern/projects': typeof ModernProjectsRoute
  '/modern/shrines': typeof ModernShrinesRoute
  '/ui-kit/slider': typeof UiKitSliderRoute
  '/ui-kit/webgl-tentacle-footer': typeof UiKitWebglTentacleFooterRoute
  '/modern/': typeof ModernIndexRoute
  '/ui-kit/': typeof UiKitIndexRoute
  '/modern/case-studies/$slug': typeof ModernCaseStudiesSlugRoute
  '/modern/case-studies/': typeof ModernCaseStudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/art': typeof ArtRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/shrines': typeof ShrinesRoute
  '/modern/about': typeof ModernAboutRoute
  '/modern/art': typeof ModernArtRoute
  '/modern/contact': typeof ModernContactRoute
  '/modern/experience': typeof ModernExperienceRoute
  '/modern/projects': typeof ModernProjectsRoute
  '/modern/shrines': typeof ModernShrinesRoute
  '/ui-kit/slider': typeof UiKitSliderRoute
  '/ui-kit/webgl-tentacle-footer': typeof UiKitWebglTentacleFooterRoute
  '/modern': typeof ModernIndexRoute
  '/ui-kit': typeof UiKitIndexRoute
  '/modern/case-studies/$slug': typeof ModernCaseStudiesSlugRoute
  '/modern/case-studies': typeof ModernCaseStudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modern': typeof ModernRouteRouteWithChildren
  '/ui-kit': typeof UiKitRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/art': typeof ArtRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/shrines': typeof ShrinesRoute
  '/modern/about': typeof ModernAboutRoute
  '/modern/art': typeof ModernArtRoute
  '/modern/case-studies': typeof ModernCaseStudiesRouteWithChildren
  '/modern/contact': typeof ModernContactRoute
  '/modern/experience': typeof ModernExperienceRoute
  '/modern/projects': typeof ModernProjectsRoute
  '/modern/shrines': typeof ModernShrinesRoute
  '/ui-kit/slider': typeof UiKitSliderRoute
  '/ui-kit/webgl-tentacle-footer': typeof UiKitWebglTentacleFooterRoute
  '/modern/': typeof ModernIndexRoute
  '/ui-kit/': typeof UiKitIndexRoute
  '/modern/case-studies/$slug': typeof ModernCaseStudiesSlugRoute
  '/modern/case-studies/': typeof ModernCaseStudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/modern'
    | '/ui-kit'
    | '/about'
    | '/art'
    | '/case-studies'
    | '/contact'
    | '/experience'
    | '/projects'
    | '/shrines'
    | '/modern/about'
    | '/modern/art'
    | '/modern/case-studies'
    | '/modern/contact'
    | '/modern/experience'
    | '/modern/projects'
    | '/modern/shrines'
    | '/ui-kit/slider'
    | '/ui-kit/webgl-tentacle-footer'
    | '/modern/'
    | '/ui-kit/'
    | '/modern/case-studies/$slug'
    | '/modern/case-studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/art'
    | '/case-studies'
    | '/contact'
    | '/experience'
    | '/projects'
    | '/shrines'
    | '/modern/about'
    | '/modern/art'
    | '/modern/contact'
    | '/modern/experience'
    | '/modern/projects'
    | '/modern/shrines'
    | '/ui-kit/slider'
    | '/ui-kit/webgl-tentacle-footer'
    | '/modern'
    | '/ui-kit'
    | '/modern/case-studies/$slug'
    | '/modern/case-studies'
  id:
    | '__root__'
    | '/'
    | '/modern'
    | '/ui-kit'
    | '/about'
    | '/art'
    | '/case-studies'
    | '/contact'
    | '/experience'
    | '/projects'
    | '/shrines'
    | '/modern/about'
    | '/modern/art'
    | '/modern/case-studies'
    | '/modern/contact'
    | '/modern/experience'
    | '/modern/projects'
    | '/modern/shrines'
    | '/ui-kit/slider'
    | '/ui-kit/webgl-tentacle-footer'
    | '/modern/'
    | '/ui-kit/'
    | '/modern/case-studies/$slug'
    | '/modern/case-studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModernRouteRoute: typeof ModernRouteRouteWithChildren
  UiKitRouteRoute: typeof UiKitRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArtRoute: typeof ArtRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  ProjectsRoute: typeof ProjectsRoute
  ShrinesRoute: typeof ShrinesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shrines': {
      id: '/shrines'
      path: '/shrines'
      fullPath: '/shrines'
      preLoaderRoute: typeof ShrinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art': {
      id: '/art'
      path: '/art'
      fullPath: '/art'
      preLoaderRoute: typeof ArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-kit': {
      id: '/ui-kit'
      path: '/ui-kit'
      fullPath: '/ui-kit'
      preLoaderRoute: typeof UiKitRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modern': {
      id: '/modern'
      path: '/modern'
      fullPath: '/modern'
      preLoaderRoute: typeof ModernRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-kit/': {
      id: '/ui-kit/'
      path: '/'
      fullPath: '/ui-kit/'
      preLoaderRoute: typeof UiKitIndexRouteImport
      parentRoute: typeof UiKitRouteRoute
    }
    '/modern/': {
      id: '/modern/'
      path: '/'
      fullPath: '/modern/'
      preLoaderRoute: typeof ModernIndexRouteImport
      parentRoute: typeof ModernRouteRoute
    }
    '/ui-kit/webgl-tentacle-footer': {
      id: '/ui-kit/webgl-tentacle-footer'
      path: '/webgl-tentacle-footer'
      fullPath: '/ui-kit/webgl-tentacle-footer'
      preLoaderRoute: typeof UiKitWebglTentacleFooterRouteImport
      parentRoute: typeof UiKitRouteRoute
    }
    '/ui-kit/slider': {
      id: '/ui-kit/slider'
      path: '/slider'
      fullPath: '/ui-kit/slider'
      preLoaderRoute: typeof UiKitSliderRouteImport
      parentRoute: typeof UiKitRouteRoute
    }
    '/modern/shrines': {
      id: '/modern/shrines'
      path: '/shrines'
      fullPath: '/modern/shrines'
      preLoaderRoute: typeof ModernShrinesRouteImport
      parentRoute: typeof ModernRouteRoute
    }
    '/modern/projects': {
      id: '/modern/projects'
      path: '/projects'
      fullPath: '/modern/projects'
      preLoaderRoute: typeof ModernProjectsRouteImport
      parentRoute: typeof ModernRouteRoute
    }
    '/modern/experience': {
      id: '/modern/experience'
      path: '/experience'
      fullPath: '/modern/experience'
      preLoaderRoute: typeof ModernExperienceRouteImport
      parentRoute: typeof ModernRouteRoute
    }
    '/modern/contact': {
      id: '/modern/contact'
      path: '/contact'
      fullPath: '/modern/contact'
      preLoaderRoute: typeof ModernContactRouteImport
      parentRoute: typeof ModernRouteRoute
    }
    '/modern/case-studies': {
      id: '/modern/case-studies'
      path: '/case-studies'
      fullPath: '/modern/case-studies'
      preLoaderRoute: typeof ModernCaseStudiesRouteImport
      parentRoute: typeof ModernRouteRoute
    }
    '/modern/art': {
      id: '/modern/art'
      path: '/art'
      fullPath: '/modern/art'
      preLoaderRoute: typeof ModernArtRouteImport
      parentRoute: typeof ModernRouteRoute
    }
    '/modern/about': {
      id: '/modern/about'
      path: '/about'
      fullPath: '/modern/about'
      preLoaderRoute: typeof ModernAboutRouteImport
      parentRoute: typeof ModernRouteRoute
    }
    '/modern/case-studies/': {
      id: '/modern/case-studies/'
      path: '/'
      fullPath: '/modern/case-studies/'
      preLoaderRoute: typeof ModernCaseStudiesIndexRouteImport
      parentRoute: typeof ModernCaseStudiesRoute
    }
    '/modern/case-studies/$slug': {
      id: '/modern/case-studies/$slug'
      path: '/$slug'
      fullPath: '/modern/case-studies/$slug'
      preLoaderRoute: typeof ModernCaseStudiesSlugRouteImport
      parentRoute: typeof ModernCaseStudiesRoute
    }
  }
}

interface ModernCaseStudiesRouteChildren {
  ModernCaseStudiesSlugRoute: typeof ModernCaseStudiesSlugRoute
  ModernCaseStudiesIndexRoute: typeof ModernCaseStudiesIndexRoute
}

const ModernCaseStudiesRouteChildren: ModernCaseStudiesRouteChildren = {
  ModernCaseStudiesSlugRoute: ModernCaseStudiesSlugRoute,
  ModernCaseStudiesIndexRoute: ModernCaseStudiesIndexRoute,
}

const ModernCaseStudiesRouteWithChildren =
  ModernCaseStudiesRoute._addFileChildren(ModernCaseStudiesRouteChildren)

interface ModernRouteRouteChildren {
  ModernAboutRoute: typeof ModernAboutRoute
  ModernArtRoute: typeof ModernArtRoute
  ModernCaseStudiesRoute: typeof ModernCaseStudiesRouteWithChildren
  ModernContactRoute: typeof ModernContactRoute
  ModernExperienceRoute: typeof ModernExperienceRoute
  ModernProjectsRoute: typeof ModernProjectsRoute
  ModernShrinesRoute: typeof ModernShrinesRoute
  ModernIndexRoute: typeof ModernIndexRoute
}

const ModernRouteRouteChildren: ModernRouteRouteChildren = {
  ModernAboutRoute: ModernAboutRoute,
  ModernArtRoute: ModernArtRoute,
  ModernCaseStudiesRoute: ModernCaseStudiesRouteWithChildren,
  ModernContactRoute: ModernContactRoute,
  ModernExperienceRoute: ModernExperienceRoute,
  ModernProjectsRoute: ModernProjectsRoute,
  ModernShrinesRoute: ModernShrinesRoute,
  ModernIndexRoute: ModernIndexRoute,
}

const ModernRouteRouteWithChildren = ModernRouteRoute._addFileChildren(
  ModernRouteRouteChildren,
)

interface UiKitRouteRouteChildren {
  UiKitSliderRoute: typeof UiKitSliderRoute
  UiKitWebglTentacleFooterRoute: typeof UiKitWebglTentacleFooterRoute
  UiKitIndexRoute: typeof UiKitIndexRoute
}

const UiKitRouteRouteChildren: UiKitRouteRouteChildren = {
  UiKitSliderRoute: UiKitSliderRoute,
  UiKitWebglTentacleFooterRoute: UiKitWebglTentacleFooterRoute,
  UiKitIndexRoute: UiKitIndexRoute,
}

const UiKitRouteRouteWithChildren = UiKitRouteRoute._addFileChildren(
  UiKitRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModernRouteRoute: ModernRouteRouteWithChildren,
  UiKitRouteRoute: UiKitRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ArtRoute: ArtRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  ProjectsRoute: ProjectsRoute,
  ShrinesRoute: ShrinesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
